import type { Metadata } from "next";
import { Jost, Hanalei_Fill, Josefin_Sans } from "next/font/google";
import "./globals.css";
import Header from "../components/header/Header";
import Footer from "@/components/footer/Footer";

export const hanalei_fill = Hanalei_Fill({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: "400",
});

const jost = Jost({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const josefinSans = Josefin_Sans({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Maximilian Jaroscak",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jost.className} antialiased `}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
