name: Docker Image CI
permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        if: github.event_name == 'push'
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ghcr.io/masterpiecesvk/portfolio:latest

      - name: Push the Docker image
        if: github.event_name == 'push'
        run: docker push ghcr.io/masterpiecesvk/portfolio:latest
